services:
  backend:
    user: "33:33"
    build: .
    container_name: symfony_app
    restart: always
    volumes:
      - .:/var/www/html
      - ./var/log:/var/www/html/var/log
    ports:
      - "8001:80"
    depends_on:
      - database
    env_file:
      - .env
    entrypoint: ["/entrypoint.sh"]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"    # puerto AMQP (para apps)
      - "15672:15672"  # puerto de la consola web
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  database:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: credit_cards
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  rabbitmq_data:
