security:
    firewalls:
        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Auth\Infrastructure\Security\TokenAuthenticator

    access_control:
        - { path: ^/api, roles: PUBLIC_ACCESS }
        - { path: ^/api/protected, roles: IS_AUTHENTICATED_FULLY }
